version: "3.8"

services:
  api:
    build: 
      context: ./
      dockerfile: ./docker/development.Dockerfile
    container_name: nestjs_skeleton
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5000:8080"
      - "9229:9229"
    depends_on: 
      - db

  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: test_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3307:3306"

volumes:
  db_data:
